### PR TITLE
Added async version suitable for home-assistant

### PR DESCRIPTION
**Pull request by mexx42**
Hi Gransi,

i added async stuff so that it can now be used within home-assistant. 

the home.assistant integration is pending, but already working for me locally. To make a PR in home-assistant i need a python package on pypi i can reference - thats the rules :(

i use only Client.request and found out that obviously the timestamp in the awattar api feed is localtime not utc (*argh*)

i assume that therefore Client.today() is currently not working as expected - see examples - as currently we have "normal time" and Client.tomorrow() is ok.

I didnt add all the typing stuff to the new classes, as i merged from an older version. however, i should do it ;)

hopefully you are ok with my changes and we can make a new version with the async stuff :)

another question: how do you use __max__() and __min__() ? max(Client).price_per_kWh does not work ... for me "max()" and "min()" is perfectly ok ...

regards,
marcus.

### CODE REVIEW

**Comment by mexx42** [comment]
Hi Gransi,

can you please comment on the PR as i want to make a PR for home-assistant also, and having a python module available on pypi is mandatory for acceptance in home-assistant.

btw: with this and my integration i am already automatically charging my batteries at lowest rates ;) 

regards,
marcus.

**Comment by Gransi** [comment]
Hi marcus,

thanks for your PR! Currently I'm reworking the code to get package to a stable version with pytest, ruff and mypy. During the testing I found some conditions where the package return wrong values. I hope in the next days I can release a new stable version

best regards
Gransi

**Comment by mexx42** [comment]
Thank you, great ! - please let me know if i can assist in any way !

**Comment by Gransi** [comment]
New version is online! :)

**Pull request merged**
